f1=input("Enter the Fruit 1")
f2=input("Enter the Fruit 2")
f3=input("Enter the Fruit 3")
f4=input("Enter the Fruit 4")
f5=input("Enter the Fruit 5")
f6=input("Enter the Fruit 6")
f7=input("Enter the Fruit 7")
myfruit=(f1,f2,f3,f4,f5,f6,f7)
print(myfruit)